### ISSUE TITLE
moc3 format discussion

### ISSUE THREAD

**Issue by wzhgba** [UlyssesWu/FreeLive#1]
It seems moc3 file is offset based format.
Start from 0x40 of the file (in my downloaded sample), list of int32 values indicate buffer offset on this file and the list ends with 0. I guess the challenge is to parse each data blocks split by the offset list.
It will be great if you share any previous investigation and conclusion on this format.

**Comment by UlyssesWu** [comment]
Sadly, I have always been working on v2 which has enough info to implement. As for v3 (moc3),  there is no guide like your articles. I will continue looking into the editor, but still I don't know if all moc3 related code is implemented in native side.

It seems that v3 implemented more features, especially [deformers](https://www.live2d.com/en/products/cubism3) (Path Deformer, Warp Deformer etc.), which are impossible to be inferred from v2.

**Comment by wzhgba** [comment]
It takes time to try different features, save files, compare data different and guess the format.

**Comment by UlyssesWu** [comment]
Trying is a way, of course, but I can't believe you had figured out the moc format just by trying like that.  You might have used some RE techs and I'd try something similar.

**Comment by UlyssesWu** [comment]
Progress Update: I think I've figured out a clear way to reverse it but it does require plenty of time, and maybe knowledge about kotlin. I also created a table to record all these formats focused by FreeLive project.

https://github.com/UlyssesWu/FreeLive/wiki/L2-Format-Table

**Comment by UlyssesWu** [comment]
I'm glad to announce that I've finally finished the _MOC3 Genome Project_ , which means moc3 can be parsed now. This project is time-wasting and boring - I've spent (almost) all my spare time in July in order to finish it.

If you have interests on my implementations, you can ask me via Q.

I'll continue to perform some deeper internal research such as #2 . However it won't be open for a while. If someone I've known would like to participate, contact me via email or Q.
